{% set name = "clickqt" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clickqt-{{ version }}.tar.gz
  sha256: 08fd460d70797be8e5799225532a0c5c46f3dc0eee6da2efeeab47402f92ae4d

build:
  entry_points:
    - clickqtfy = clickqt.__main__:clickqtfy
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=51
    - setuptools-scm >=6
    - pip
  run:
    - python >=3.8
    - click
    - pyside6

test:
  imports:
    - clickqt

about:
  home: https://github.com/ssciwr/clickqt
  summary: Turn click CLI's into QT applications
  license: MIT
  license_file:
    - COPYING.md
    - LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
