{% set name = "clickqt" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/clickqt-{{ version }}.tar.gz
  sha256: 5ec4d6a10e8ce1a3200f63b464c0c579c1ed59cfb88a19cc2ade3aecd7a53b47

build:
  entry_points:
    - clickqtfy = clickqt.__main__:clickqtfy
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=51
    - setuptools-scm >=6
    - pip
  run:
    - python >={{ python_min }}
    - click
    - pyside6
    - click-option-group
    - qt-collapsible-section-pyside6

test:
  requires:
    - python {{ python_min }}
  imports:
    - clickqt

about:
  home: https://github.com/ssciwr/clickqt
  summary: Turn click CLI's into QT applications
  license: MIT
  license_file:
    - COPYING.md
    - LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
