{% set name = "clickqt" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clickqt-{{ version }}.tar.gz
  sha256: 14c61568a69f26b8be7b3e65b9c38e69cb2377127f71865d664b5ef22f20c878

build:
  entry_points:
    - clickqtfy = clickqt.__main__:clickqtfy
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=51
    - setuptools-scm >=6
    - pip
  run:
    - python >=3.8
    - click
    - pyside6
    - click-option-group
    - qt-collapsible-section-pyside6

test:
  imports:
    - clickqt

about:
  home: https://github.com/ssciwr/clickqt
  summary: Turn click CLI's into QT applications
  license: MIT
  license_file:
    - COPYING.md
    - LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
